---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./NostalgiaForInfinityX.py:/freqtrade/NostalgiaForInfinityX.py"
    ports:
      - "8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/pairlist-volume-binance-usdt.json
      --config /freqtrade/user_data/blacklist-binance.json
      --config /freqtrade/user_data/exampleconfig-rebuy.json
      --config /freqtrade/user_data/exampleconfig_secret.json
      --strategy NostalgiaForInfinityX
  dryrun:
    image: freqtradeorg/freqtrade:stable
    #build:
    #  context: .
    #  dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-dryrun
    ports:
    - "8081:8080"
    volumes:
    - "./user_data:/freqtrade/user_data"
    - "./NostalgiaForInfinityX.py:/freqtrade/NostalgiaForInfinityX.py"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade-dryrun.log
      --db-url sqlite:////freqtrade/user_data/tradesv3-dryrun.sqlite
      --config user_data/data/blacklist-kucoin.json
      --config user_data/data/pairlist-volume-kucoin-usdt.json
      --config user_data/data/exampleconfig_secret.json
      --config user_data/data/exampleconfig-rebuy.json      
      --strategy NostalgiaForInfinityX
      --dry-run
  backtesting:
    image: freqtradeorg/freqtrade:stable
    #build:
    #  context: .
    #  dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
    - "./user_data:/freqtrade/user_data"
    - "./NostalgiaForInfinityX.py:/freqtrade/NostalgiaForInfinityX.py"
    command: >
      backtesting
      --datadir user_data/data/${EXCHANGE:-binance}
      --strategy-list NostalgiaForInfinityX
      --timerange ${TIMERANGE:-20211201-20220115}
      --config user_data/data/pairlists.json
      --config user_data/data/${EXCHANGE:-binance}-usdt-static.json
      --max-open-trades ${MAX_OPEN_TRADES:-5}
      --stake-amount ${STAKE_AMOUNT:-unlimited}
